### PR TITLE
satyam.html file by satyam

### PR DESCRIPTION
**Pull request by SatyamPrajapati07575**
hi Satyendra bhai review this code and add your repo

### CODE REVIEW

**Review by satendarpal321455 — COMMENTED** [review]
Ye code kya karta he

**Comment by SatyamPrajapati07575** [comment]
Bahut mst kam karta hai

**Comment by satendarpal321455** [comment]
Thanks bhai batane ke liye

**Comment by SatyamPrajapati07575** [comment]
Satyendra bhai ye Heading ko h1 me dikhayega

**Comment by satendarpal321455** [comment]
Satyam bhai h1 dikhayega  upki bat thik he

**Pull request merged**
